"""City policy SoT → generated vendor settings (pc-1059).

Principle (same family as skills_sync / generate-don't-document):

* **SoT** lives under the city tree: ``.agents/policy/permissions.json``
* **Vendor mirrors** (``.claude/settings.json`` permissions) are generated —
  never hand-authored. Host-personal overrides stay in
  ``.claude/settings.local.json`` (never touched by this module).
* **Drift check** regenerates the expected mirror and compares.

v1 scope: Claude settings permissions allow/deny (+ optional
``enableAllProjectMcpServers``). Codex/Grok mirrors are reserved for a
follow-on slice (schema already notes them).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

POLICY_REL = Path(".agents") / "policy" / "permissions.json"
POLICY_README_REL = Path(".agents") / "policy" / "README.md"
CLAUDE_SETTINGS_REL = Path(".claude") / "settings.json"
GENERATED_BY = "policy_sync"
SCHEMA_VERSION = 1

# Retired Claude MCP grants. mcp_sync already strips the ticketingprotocol
# server (pc-1079); keeping the allow entry makes Claude expect a ghost.
RETIRED_MCP_ALLOWS: Tuple[str, ...] = ("mcp__ticketingprotocol",)

# Safe default for fresh cities (matches the historical thin city settings face).
DEFAULT_ALLOW: List[str] = [
    "mcp__worklane",
    "WebSearch",
    "Bash(git status:*)",
    "Bash(git log:*)",
    "Bash(git diff:*)",
    "Bash(git show:*)",
    "Bash(git branch:*)",
    "Bash(ls:*)",
    "Bash(cat:*)",
    "Bash(head:*)",
    "Bash(tail:*)",
    "Bash(wc:*)",
    "Bash(grep:*)",
    "Bash(rg:*)",
    "Bash(find:*)",
    "Bash(curl -s --max-time 5 http://127.0.0.1:8797:*)",
    "Bash(curl -s --max-time 5 http://127.0.0.1:8799:*)",
    "Bash(curl -s --max-time 5 http://localhost:8797:*)",
    "Bash(curl -s --max-time 5 http://localhost:8799:*)",
]

DEFAULT_DENY: List[str] = [
    "Bash(git add -A:*)",
    "Bash(git add .)",
    "Bash(git commit -a:*)",
]


def _pkg_dir() -> Path:
    return Path(__file__).resolve().parent


def _repo_root() -> Path:
    return _pkg_dir().parent


def _templates_dir() -> Path:
    packaged = _pkg_dir() / "templates"
    if packaged.is_dir():
        return packaged
    monorepo = _repo_root() / "templates"
    if monorepo.is_dir():
        return monorepo
    return packaged


def default_policy() -> Dict[str, Any]:
    """Return the canonical default policy paper (dict)."""
    return {
        "version": SCHEMA_VERSION,
        "description": (
            "City permissions SoT (pc-1059). Vendor settings are generated by "
            "policy_sync; host-personal overrides live only in "
            ".claude/settings.local.json."
        ),
        "path_boundaries": {
            "respect_files": ["BOUNDARIES.md", "PERIMETER.md"],
            "notes": (
                "ADR-056: tradeOS must not import WorkLane runtime. "
                "Hands never commit across project boundaries under this identity."
            ),
        },
        "command_classes": {
            "allow": list(DEFAULT_ALLOW),
            "deny": list(DEFAULT_DENY),
        },
        "hooks": [],
        "capability_tiers": {
            "default": "implement",
            "notes": (
                "Per-seat tiers reserved for a future MCP gateway; "
                "Claude city settings are workspace-wide in v1."
            ),
        },
        "vendor_mirrors": {
            "claude": {
                "path": ".claude/settings.json",
                "format": "claude_settings_v1",
                "status": "active",
            },
            "codex": {
                "path": ".codex/config.toml",
                "format": "reserved",
                "status": "reserved",
            },
            "grok": {
                "path": ".grok/config.toml",
                "format": "reserved",
                "status": "reserved",
            },
        },
    }


def policy_path(workspace: Path) -> Path:
    return workspace.expanduser().resolve() / POLICY_REL


def claude_settings_path(workspace: Path) -> Path:
    return workspace.expanduser().resolve() / CLAUDE_SETTINGS_REL


def _as_str_list(value: Any) -> List[str]:
    if not isinstance(value, list):
        return []
    out: List[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            out.append(item.strip())
        elif isinstance(item, dict):
            # Allow {id, pattern} or {id, patterns: [...]}
            pat = item.get("pattern")
            if isinstance(pat, str) and pat.strip():
                out.append(pat.strip())
            pats = item.get("patterns")
            if isinstance(pats, list):
                for p in pats:
                    if isinstance(p, str) and p.strip():
                        out.append(p.strip())
    return out


def load_policy(workspace: Path) -> Dict[str, Any]:
    """Load policy SoT; raises FileNotFoundError / ValueError on bad paper."""
    path = policy_path(workspace)
    if not path.is_file():
        raise FileNotFoundError("policy SoT missing: %s" % path)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError("policy SoT is not valid JSON: %s (%s)" % (path, exc)) from exc
    if not isinstance(data, dict):
        raise ValueError("policy SoT root must be an object: %s" % path)
    return data


def normalize_policy(data: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize allow/deny lists for stable compare + generate."""
    classes = data.get("command_classes") if isinstance(data.get("command_classes"), dict) else {}
    allow = [
        s
        for s in _as_str_list(classes.get("allow") if isinstance(classes, dict) else None)
        if s not in RETIRED_MCP_ALLOWS
    ]
    deny = _as_str_list(classes.get("deny") if isinstance(classes, dict) else None)
    # Stable unique order (first-seen)
    def _uniq(seq: Sequence[str]) -> List[str]:
        seen = set()
        out: List[str] = []
        for s in seq:
            if s not in seen:
                seen.add(s)
                out.append(s)
        return out

    out = dict(data)
    out["version"] = int(data.get("version") or SCHEMA_VERSION)
    out["command_classes"] = {
        "allow": _uniq(allow),
        "deny": _uniq(deny),
    }
    if "hooks" not in out or not isinstance(out.get("hooks"), list):
        out["hooks"] = []
    return out


def render_claude_settings(policy: Dict[str, Any]) -> Dict[str, Any]:
    """Project policy paper → Claude Code settings.json object."""
    p = normalize_policy(policy)
    classes = p["command_classes"]
    body: Dict[str, Any] = {
        "permissions": {
            "allow": list(classes["allow"]),
            "deny": list(classes["deny"]),
        },
        "enableAllProjectMcpServers": True,
        "blueprint": {
            "generated_by": GENERATED_BY,
            "source": str(POLICY_REL).replace("\\", "/"),
            "version": int(p.get("version") or SCHEMA_VERSION),
        },
    }
    return body


def dumps_settings(body: Dict[str, Any]) -> str:
    return json.dumps(body, indent=2, sort_keys=False) + "\n"


def canonicalize_settings(body: Dict[str, Any]) -> str:
    """Stable string for drift compare (ignore key order noise)."""
    # Compare only the surfaces policy_sync owns.
    perms = body.get("permissions") if isinstance(body.get("permissions"), dict) else {}
    allow = perms.get("allow") if isinstance(perms, dict) else []
    deny = perms.get("deny") if isinstance(perms, dict) else []
    if not isinstance(allow, list):
        allow = []
    if not isinstance(deny, list):
        deny = []
    slim = {
        "permissions": {
            "allow": allow,
            "deny": deny,
        },
        "enableAllProjectMcpServers": bool(
            body.get("enableAllProjectMcpServers", True)
        ),
        "blueprint": {
            "generated_by": GENERATED_BY,
            "source": str(POLICY_REL).replace("\\", "/"),
            "version": int(
                ((body.get("blueprint") or {}) if isinstance(body.get("blueprint"), dict) else {}).get(
                    "version", SCHEMA_VERSION
                )
            ),
        },
    }
    return json.dumps(slim, sort_keys=True, separators=(",", ":"))


def expected_settings_body(workspace: Path) -> Dict[str, Any]:
    return render_claude_settings(load_policy(workspace))


def check_drift(workspace: Path) -> Dict[str, Any]:
    """Return ok/drift for Claude settings vs policy SoT."""
    root = workspace.expanduser().resolve()
    result: Dict[str, Any] = {
        "ok": False,
        "workspace": str(root),
        "policy": str(policy_path(root)),
        "settings": str(claude_settings_path(root)),
        "drift": True,
        "detail": "",
    }
    try:
        expected = expected_settings_body(root)
    except FileNotFoundError as exc:
        result["detail"] = str(exc)
        return result
    except ValueError as exc:
        result["detail"] = str(exc)
        return result

    path = claude_settings_path(root)
    if not path.is_file():
        result["detail"] = "missing generated mirror: %s" % path
        return result
    try:
        on_disk = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        result["detail"] = "settings.json is not valid JSON: %s" % exc
        return result
    if not isinstance(on_disk, dict):
        result["detail"] = "settings.json root must be an object"
        return result

    if canonicalize_settings(on_disk) == canonicalize_settings(expected):
        result["ok"] = True
        result["drift"] = False
        result["detail"] = "ok: Claude settings match policy SoT"
        return result

    result["detail"] = (
        "drift: %s does not match %s — run policy_sync apply "
        "(or restore SoT; do not hand-edit the generated mirror)"
        % (CLAUDE_SETTINGS_REL, POLICY_REL)
    )
    return result


def apply_policy(
    workspace: Path,
    *,
    force: bool = True,
) -> Dict[str, Any]:
    """Write Claude settings.json from policy SoT. Never touches settings.local.json."""
    root = workspace.expanduser().resolve()
    path = claude_settings_path(root)
    expected = expected_settings_body(root)
    text = dumps_settings(expected)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and not force:
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
            if (
                isinstance(existing, dict)
                and canonicalize_settings(existing) == canonicalize_settings(expected)
            ):
                return {
                    "ok": True,
                    "action": "skipped",
                    "path": str(path),
                    "detail": "already in sync",
                }
        except (json.JSONDecodeError, OSError):
            pass
    path.write_text(text, encoding="utf-8")
    return {
        "ok": True,
        "action": "wrote",
        "path": str(path),
        "detail": "generated Claude settings from policy SoT",
    }


def import_from_settings(workspace: Path, *, force: bool = False) -> Dict[str, Any]:
    """Seed policy SoT from an existing .claude/settings.json (migration helper).

    Never copies secret values. Only permissions allow/deny lists.
    """
    root = workspace.expanduser().resolve()
    settings_p = claude_settings_path(root)
    policy_p = policy_path(root)
    if not settings_p.is_file():
        return {
            "ok": False,
            "action": "error",
            "detail": "no settings to import: %s" % settings_p,
        }
    if policy_p.is_file() and not force:
        return {
            "ok": True,
            "action": "skipped",
            "path": str(policy_p),
            "detail": "policy SoT already exists (pass force=True to overwrite)",
        }
    try:
        data = json.loads(settings_p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"ok": False, "action": "error", "detail": "bad settings JSON: %s" % exc}
    if not isinstance(data, dict):
        return {"ok": False, "action": "error", "detail": "settings root must be object"}
    perms = data.get("permissions") if isinstance(data.get("permissions"), dict) else {}
    allow = _as_str_list(perms.get("allow") if isinstance(perms, dict) else None)
    deny = _as_str_list(perms.get("deny") if isinstance(perms, dict) else None)
    if not allow and not deny:
        return {
            "ok": False,
            "action": "error",
            "detail": "settings.json has empty permissions; refusing import",
        }
    paper = default_policy()
    paper["command_classes"] = {"allow": allow, "deny": deny}
    paper["description"] = (
        "City permissions SoT imported from existing .claude/settings.json "
        "(pc-1059 migration). Edit this file; re-run policy_sync apply."
    )
    policy_p.parent.mkdir(parents=True, exist_ok=True)
    policy_p.write_text(json.dumps(paper, indent=2) + "\n", encoding="utf-8")
    return {
        "ok": True,
        "action": "imported",
        "path": str(policy_p),
        "detail": "seeded policy from %s" % settings_p,
    }


def plant_policy_kit(
    workspace: Path,
    *,
    force: bool = False,
    write_settings: bool = True,
) -> Dict[str, Any]:
    """Plant policy SoT + README (+ optional first settings mirror) into a city.

    Idempotent. Safe from found / seed-ops. Does not clobber settings.local.json.
    """
    root = workspace.expanduser().resolve()
    tdir = _templates_dir()
    planted: List[str] = []
    skipped: List[str] = []

    # permissions.json
    pol_dst = policy_path(root)
    pol_src = tdir / "agents" / "policy" / "permissions.json"
    pol_dst.parent.mkdir(parents=True, exist_ok=True)
    if not pol_dst.exists() or force:
        if pol_src.is_file():
            shutil.copy2(pol_src, pol_dst)
        else:
            pol_dst.write_text(
                json.dumps(default_policy(), indent=2) + "\n", encoding="utf-8"
            )
        planted.append(str(POLICY_REL).replace("\\", "/"))
    else:
        skipped.append(str(POLICY_REL).replace("\\", "/"))

    # README
    readme_dst = root / POLICY_README_REL
    readme_src = tdir / "agents" / "policy" / "README.md"
    if not readme_dst.exists() or force:
        if readme_src.is_file():
            shutil.copy2(readme_src, readme_dst)
        else:
            readme_dst.write_text(
                "# City policy (permissions SoT)\n\n"
                "Edit `permissions.json`. Run `bash scripts/policy_sync.sh` "
                "to regenerate `.claude/settings.json`. Never hand-edit the "
                "generated mirror — use `.claude/settings.local.json` for "
                "host-personal overrides.\n",
                encoding="utf-8",
            )
        planted.append(str(POLICY_README_REL).replace("\\", "/"))
    else:
        skipped.append(str(POLICY_README_REL).replace("\\", "/"))

    # Script plant (workspace scripts/)
    scripts_dst = root / "scripts"
    scripts_dst.mkdir(parents=True, exist_ok=True)
    name = "policy_sync.sh"
    dst = scripts_dst / name
    # Prefer monorepo SoT symlink when ProtocolCity parcel present
    pc_script = root / "ProtocolCity" / "scripts" / name
    monorepo_script = _repo_root() / "scripts" / name
    src = tdir / "scripts" / name
    if not src.is_file() and monorepo_script.is_file():
        src = monorepo_script

    if (
        pc_script.is_file()
        and not pc_script.is_symlink()
        and root.name != "ProtocolCity"
    ):
        rel = os.path.relpath(pc_script, scripts_dst)
        if dst.is_symlink() and os.readlink(str(dst)) == rel and not force:
            skipped.append("scripts/%s → ProtocolCity (mirror)" % name)
        else:
            if dst.exists() and not dst.is_symlink() and not force:
                skipped.append("scripts/%s (independent copy)" % name)
            else:
                if dst.is_symlink() or dst.is_file():
                    dst.unlink()
                try:
                    os.symlink(rel, dst)
                    planted.append("scripts/%s → %s" % (name, rel))
                except OSError:
                    if src.is_file():
                        shutil.copy2(src, dst)
                        try:
                            os.chmod(dst, 0o755)
                        except OSError:
                            pass
                        planted.append("scripts/%s" % name)
    elif not dst.exists() or force:
        if src.is_file():
            shutil.copy2(src, dst)
            try:
                os.chmod(dst, 0o755)
            except OSError:
                pass
            planted.append("scripts/%s" % name)
        else:
            skipped.append("scripts/%s (template missing)" % name)
    else:
        skipped.append("scripts/%s" % name)

    settings_action = "skipped"
    if write_settings:
        settings_p = claude_settings_path(root)
        if not settings_p.exists() or force:
            try:
                apply_policy(root, force=True)
                settings_action = "wrote"
                planted.append(str(CLAUDE_SETTINGS_REL).replace("\\", "/"))
            except (FileNotFoundError, ValueError) as exc:
                settings_action = "error: %s" % exc
        else:
            # Existing settings: leave alone (host may have pre-policy content).
            # Operator can --import-from-settings then apply.
            settings_action = "left_existing"
            skipped.append(str(CLAUDE_SETTINGS_REL).replace("\\", "/"))

    return {
        "ok": True,
        "planted": planted,
        "skipped": skipped,
        "settings_action": settings_action,
        "workspace": str(root),
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="policy_sync",
        description=(
            "Generate .claude/settings.json from .agents/policy/permissions.json "
            "(pc-1059). Never edits settings.local.json."
        ),
    )
    parser.add_argument(
        "command",
        nargs="?",
        default="apply",
        choices=("apply", "check", "import", "plant", "show"),
        help="apply (default) | check | import | plant | show",
    )
    parser.add_argument(
        "--workspace",
        default="",
        help="workspace root (default: WORKSPACE_ROOT or cwd walk)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing SoT/settings when planting/importing",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.workspace:
        root = Path(args.workspace).expanduser().resolve()
    else:
        env = (
            os.environ.get("WORKSPACE_ROOT")
            or os.environ.get("BLUEPRINT_WORKSPACE")
            or os.environ.get("SUITE_CITY_ROOT")
            or ""
        )
        if env:
            root = Path(env).expanduser().resolve()
        else:
            # Prefer protocolcity.workspace when available
            try:
                from protocolcity.workspace import resolve_workspace_root

                root = resolve_workspace_root(Path.cwd())
            except Exception:
                root = Path.cwd().resolve()

    cmd = args.command
    out: Dict[str, Any]
    exit_code = 0

    if cmd == "check":
        out = check_drift(root)
        if not out.get("ok"):
            exit_code = 1
    elif cmd == "import":
        out = import_from_settings(root, force=args.force)
        if not out.get("ok"):
            exit_code = 1
    elif cmd == "plant":
        out = plant_policy_kit(root, force=args.force, write_settings=True)
    elif cmd == "show":
        try:
            policy = normalize_policy(load_policy(root))
            out = {
                "ok": True,
                "policy": policy,
                "expected_settings": render_claude_settings(policy),
            }
        except (FileNotFoundError, ValueError) as exc:
            out = {"ok": False, "detail": str(exc)}
            exit_code = 1
    else:  # apply
        try:
            out = apply_policy(root, force=True)
            # re-check
            chk = check_drift(root)
            out["check"] = chk
            if not chk.get("ok"):
                exit_code = 1
                out["ok"] = False
        except (FileNotFoundError, ValueError) as exc:
            out = {"ok": False, "detail": str(exc)}
            exit_code = 1

    if args.json:
        print(json.dumps(out, indent=2, default=str))
    else:
        if cmd == "show" and out.get("ok"):
            print(json.dumps(out.get("expected_settings"), indent=2))
        else:
            detail = out.get("detail") or out.get("action") or ""
            status = "ok" if out.get("ok") else "FAIL"
            print("%s: %s" % (status, detail))
            if out.get("path"):
                print("  path: %s" % out["path"])
            if out.get("planted"):
                for p in out["planted"]:
                    print("  planted: %s" % p)
            if out.get("drift") and not out.get("ok"):
                print("  hint: bash scripts/policy_sync.sh apply")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
